import { describe, expect, it } from 'vitest'
import { createInitialState, gameReducer } from './reducer'

describe('Project Origin navigation state machine', () => {
  it('walks through every implemented game state', () => {
    let state = createInitialState(null)
    expect(state.screen).toBe('TITLE')

    state = gameReducer(state, { type: 'NEW_GAME' })
    expect(state.screen).toBe('INTRO')
    state = gameReducer(state, { type: 'INTRO_COMPLETE' })
    expect(state.screen).toBe('NAME_ENTRY')
    state = gameReducer(state, { type: 'SET_NAME', name: 'ORI' })
    expect(state.screen).toBe('HUB')

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'cv' })
    expect(state.screen).toBe('LAB_INTERIOR')
    state = gameReducer(state, { type: 'START_DIALOGUE', key: 'cv-intro' })
    state = gameReducer(state, { type: 'DIALOGUE_COMPLETE' })
    expect(state.screen).toBe('MINIGAME')
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 1 })
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 2 })
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 3 })
    expect(state.save.stageProgress.cv).toBe(3)
    state = gameReducer(state, { type: 'COMPLETE_CV_LAB' })
    expect(state.save.stageProgress.cv).toBe(4)
    expect(state.save.completedLabs.cv).toBe(true)
    expect(state.save.achievements).toContain('MACHINES_FIRST_SIGHT')
    state = gameReducer(state, { type: 'FINISH_CV_LAB' })
    expect(state.screen).toBe('LAB_COMPLETE')
    state = gameReducer(state, { type: 'ACKNOWLEDGE_LAB_COMPLETE' })
    expect(state.hubSpawn).toBe('hub-from-cv')

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'ml' })
    state = gameReducer(state, { type: 'START_DIALOGUE', key: 'ml-intro' })
    state = gameReducer(state, { type: 'DIALOGUE_COMPLETE' })
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 1 })
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 2 })
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 3 })
    expect(state.save.stageProgress.ml).toBe(3)
    state = gameReducer(state, { type: 'COMPLETE_ML_LAB' })
    expect(state.save.stageProgress.ml).toBe(4)
    expect(state.save.completedLabs.ml).toBe(true)
    expect(state.save.achievements).toContain('PATTERN_FINDER')
    state = gameReducer(state, { type: 'FINISH_ML_LAB' })
    expect(state.screen).toBe('LAB_COMPLETE')
    state = gameReducer(state, { type: 'ACKNOWLEDGE_LAB_COMPLETE' })
    expect(state.hubSpawn).toBe('hub-from-ml')

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'nlp' })
    state = gameReducer(state, { type: 'START_DIALOGUE', key: 'nlp-intro' })
    state = gameReducer(state, { type: 'DIALOGUE_COMPLETE' })
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 1 })
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 2 })
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 3 })
    expect(state.save.stageProgress.nlp).toBe(3)
    state = gameReducer(state, { type: 'COMPLETE_NLP_LAB' })
    expect(state.save.stageProgress.nlp).toBe(4)
    expect(state.save.completedLabs.nlp).toBe(true)
    expect(state.save.achievements).toContain('LANGUAGE_DECODER')
    expect(state.save.achievements).toContain('AI_AWAKENED')
    state = gameReducer(state, { type: 'FINISH_NLP_LAB' })
    expect(state.screen).toBe('LAB_COMPLETE')
    state = gameReducer(state, { type: 'ACKNOWLEDGE_LAB_COMPLETE' })
    expect(state.hubSpawn).toBe('hub-from-nlp')

    state = gameReducer(state, { type: 'ENTER_RESEARCH_ROUTE' })
    expect(state.screen).toBe('RESEARCH_MAP')
    state = gameReducer(state, { type: 'OPEN_RESEARCH' })
    expect(state.screen).toBe('DIALOGUE')
    expect(state.dialogueKey).toBe('research-powered')
    state = gameReducer(state, { type: 'DIALOGUE_COMPLETE' })
    expect(state.screen).toBe('RESEARCH_MAP')
    state = gameReducer(state, { type: 'RETURN_TO_HUB' })
    expect(state.screen).toBe('HUB')
    expect(state.hubSpawn).toBe('hub-from-east-gate')
  })

  it('keeps research locked before all labs are complete', () => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'ENTER_RESEARCH_ROUTE' })
    expect(state.screen).toBe('RESEARCH_MAP')
    state = gameReducer(state, { type: 'OPEN_RESEARCH' })
    expect(state.screen).toBe('DIALOGUE')
    expect(state.dialogueKey).toBe('research-locked')
    state = gameReducer(state, { type: 'DIALOGUE_COMPLETE' })
    expect(state.screen).toBe('RESEARCH_MAP')
    state = gameReducer(state, { type: 'RETURN_TO_HUB' })
    expect(state.screen).toBe('HUB')
    expect(state.hubSpawn).toBe('hub-from-east-gate')
  })

  it.each(['cv', 'ml', 'nlp'] as const)('returns an early %s lab exit to its named door spawn', (lab) => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'ENTER_LAB', lab })
    state = gameReducer(state, { type: 'LEAVE_LAB' })

    expect(state.screen).toBe('HUB')
    expect(state.currentLab).toBeNull()
    expect(state.hubSpawn).toBe(`hub-from-${lab}`)
  })

  it('never moves CV progress backwards and ignores CV actions outside the CV lab', () => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 2 })
    expect(state.save.stageProgress.cv).toBe(0)

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'cv' })
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 3 })
    state = gameReducer(state, { type: 'RECORD_CV_STAGE', stage: 1 })
    expect(state.save.stageProgress.cv).toBe(3)
  })

  it('never moves ML progress backwards and ignores ML actions outside the ML lab', () => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 2 })
    expect(state.save.stageProgress.ml).toBe(0)

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'ml' })
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 3 })
    state = gameReducer(state, { type: 'RECORD_ML_STAGE', stage: 1 })
    expect(state.save.stageProgress.ml).toBe(3)
  })

  it('never moves NLP progress backwards and ignores NLP actions outside the NLP lab', () => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 2 })
    expect(state.save.stageProgress.nlp).toBe(0)

    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'nlp' })
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 3 })
    state = gameReducer(state, { type: 'RECORD_NLP_STAGE', stage: 1 })
    expect(state.save.stageProgress.nlp).toBe(3)
  })

  it('awards AI Awakened no matter which foundation lab is completed last', () => {
    let state = createInitialState(null)
    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'nlp' })
    state = gameReducer(state, { type: 'COMPLETE_NLP_LAB' })
    state = gameReducer(state, { type: 'LEAVE_LAB' })
    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'cv' })
    state = gameReducer(state, { type: 'COMPLETE_CV_LAB' })
    state = gameReducer(state, { type: 'LEAVE_LAB' })
    state = gameReducer(state, { type: 'ENTER_LAB', lab: 'ml' })
    state = gameReducer(state, { type: 'COMPLETE_ML_LAB' })

    expect(state.save.achievements).toContain('AI_AWAKENED')
    expect(state.save.achievements.filter((item) => item === 'AI_AWAKENED')).toHaveLength(1)
  })
})
